export const ADD_NEW_MESSAGE = "CHAT/ADD_NEW_MESSAGE";
export const DELETE_MESSAGE = "CHAT/DELETE_MESSAGE";
export const FETCH_MESSAGES = "CHAT/FETCH_MESSAGES";
export const FETCHED_MESSAGES = "CHAT/FETCHED_MESSAGES";
export const SHOW_EDIT = "CHAT/SHOW_EDIT";
export const HIDE_EDIT = "CHAT/HIDE_EDIT";
export const EDIT_MESSAGE = "CHAT/EDIT_MESSAGE";

export const FETCH_USERS = "ADMIN/FETCH_USERS";
export const FETCHED_USERS = "ADMIN/FETCHED_USERS";
export const ADD_USER = "ADMIN/ADD_USER";
export const EDIT_USER = "ADMIN/EDIT_USER";
export const DELETE_USER = "ADMIN/DELETE_USER";
export const SHOW_EDIT_USER_MODAL = "ADMIN/SHOW_EDIT_USER_MODAL";
export const HIDE_EDIT_USER_MODAL = "ADMIN/HIDE_EDIT_USER_MODAL";

export const LOGIN = "AUTH/LOGIN";
export const SET_USER = "AUTH/SET_USER";
export const SET_ADMIN = "AUTH/SET_ADMIN";

export const CHANGE_HEADER_DATA = "HEADER/CHANGE_HEADER_DATA";

export const SHOW_ERROR = "API/SHOW_ERROR";